 ```yaml
   services:
     wordpress:
       image: wordpress:latest
       restart: always
       ports:
         - "8080:80"
       environment:
         WORDPRESS_DB_HOST: database-1.clgmyqs0asc5.us-east-1.rds.amazonaws.com:3306
         WORDPRESS_DB_USER: admin
         WORDPRESS_DB_PASSWORD: nicole1010
         WORDPRESS_DB_NAME: bancodd
       volumes:
         - wordpress:/var/www/html

   volumes:
     wordpress:
